#!/bin/bash
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (C) 2012 Ivan Rodriguez Murillo <wantez@gmail.com>. All rights reserved.
#
# Licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

set -e

DIR=`dirname "$0"`
cd "$DIR/../.."
APPDIR=`pwd`
cd - > /dev/null

LNDIR=/tmp/iromu/VisualSFM.app

if [ ! -e "$LNDIR/Contents/Resources/bin/VisualSFM" ]; then
	rm -f "$LNDIR"
	mkdir -p /tmp/iromu
	chmod a+w /tmp/iromu
	ln -s "$APPDIR" "$LNDIR"
fi

exec "$LNDIR/Contents/Resources/bin/VisualSFM"