#!/bin/bash
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (C) 2012 Ivan Rodriguez Murillo <wantez@gmail.com>. All rights reserved.
#
# Licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

set -e

ROOT=/tmp/iromu
APP_ROOT=${ROOT}/VisualSFM.app
HOMEBREW=${APP_ROOT}/Contents/Resources

BUILDDIR=~/src/homebrew/vsfm

function macports_deactivate() {
	if [ -e /opt/local ]; then
		echo "Macports omitted"
		sudo mv /opt/local ~/macports
	fi
}

function macports_activate() {
	if [ -e ~/macports ]; then
		echo "Macports restored"
		sudo mv  ~/macports /opt/local
	fi
}