#!/bin/bash
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (C) 2012 Ivan Rodriguez Murillo <wantez@gmail.com>. All rights reserved.
#
# Licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

set -e

scriptPath=${0%/*}

source "$scriptPath/common"

BUILD_RES=$APP_RES
FINAL_APP=VisualSFM.app
FINAL_APP_RES="$FINAL_APP/Contents/Resources"


echo "Preparing app dir"
rm -fr "$FINAL_APP"
cp -R "$scriptPath/../template_app" "$FINAL_APP"

echo "Copying Cellar dir..."
cp -R "$BUILD_RES/Cellar" "$FINAL_APP_RES/"

echo "Copying etc dir..."
cp -R "$BUILD_RES/etc" "$FINAL_APP_RES/"

echo "Copying lib dir..."
cp -R "$BUILD_RES/lib" "$FINAL_APP_RES/"

echo "Copying share dir..."
cp -R "$BUILD_RES/share" "$FINAL_APP_RES/"

echo "Copying main binary..."
cp "vsfm/bin/VisualSFM" "$FINAL_APP_RES/bin/"


echo "Copying SiftGPU library..."
cp "SiftGPU/bin/libsiftgpu.so" "$FINAL_APP_RES/bin/"

echo "Copying PBA library..."
cp "pba/bin/libpba_no_gpu.so" "$FINAL_APP_RES/bin/libpba.so"

echo "Copying CMVS/PMVS2/genOption binaries..."
cp "cmvs/program/main/cmvs" "$FINAL_APP_RES/bin/"
cp "cmvs/program/main/pmvs2" "$FINAL_APP_RES/bin/"
cp "cmvs/program/main/genOption" "$FINAL_APP_RES/bin/"

echo "Cleaning unused files"
rm -fr "$FINAL_APP_RES/Cellar/boost"
rm -fr "$FINAL_APP_RES/lib/libboost*"
rm -fr "$FINAL_APP_RES/Cellar/pkg-config"
rm -fr "$FINAL_APP_RES/lib/pkgconfig"

echo "Disconnecting BUILDDIR"
if [ -e "$APP_ROOT" ]; then 
	mkdir -p "$ATTIC"
	mv "${APP_ROOT}" "$ATTIC"
fi