#!/bin/bash
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (C) 2012 Ivan Rodriguez Murillo <wantez@gmail.com>. All rights reserved.
#
# Licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

set -e

scriptPath=${0%/*}

source $scriptPath/common

if [ ! -e "${ROOT}" ]; then
	$(mkdir -p ${ROOT})
fi

#if [ -e "$ATTIC" ]; then 
#	echo "Restoring $ATTIC to $APP_ROOT"
#	mv "$ATTIC/VisualSFM.app" "$APP_ROOT" 
#else
	mkdir -p "$APP_ROOT"
#fi


function rollback() {
	echo "Rollback"
	#macports_activate
	#if [ -e "$APP_ROOT" ]; then 
	#	echo "Moving $APP_ROOT to $ATTIC"
	#	mkdir -p "$ATTIC"
	#	mv "${APP_ROOT}" "${ATTIC}"
	#fi
	exit
}


function install_brew () {
	if [ ! -e "$APP_RES/bin/brew" ]; then
		echo "Installing Homebrew into $APP_RES"
		mkdir -p ${APP_RES} && curl -L https://github.com/mxcl/homebrew/tarball/master | tar xz --strip 1 -C ${APP_RES}
	fi
	echo $PATH | grep -q Contents/Resources/bin || export PATH="$APP_RES/bin:$APP_RES/sbin:$PATH"
}

function install_brew_libs () {
	echo "Installing Homebrew dependencies into $APP_RES"
	if [ ! -h "$APP_RES/bin/pkg-config" ]; then	
		$APP_RES/bin/brew install pkg-config	
		$APP_RES/bin/brew install jpeg
		$APP_RES/bin/brew install gdk-pixbuf --use-llvm
		$APP_RES/bin/brew install cairo
		$APP_RES/bin/brew link cairo		
	    $APP_RES/bin/brew install freetype
		$APP_RES/bin/brew link freetype
		$APP_RES/bin/brew install pango
		$APP_RES/bin/brew install fontconfig
		$APP_RES/bin/brew link pixman
		$APP_RES/bin/brew link fontconfig
	    $APP_RES/bin/brew install gtk+
		$APP_RES/bin/brew install glew
		$APP_RES/bin/brew install devil
		$APP_RES/bin/brew install gsl
		$APP_RES/bin/brew install boost
	fi

}

trap rollback INT TERM EXIT

install_brew

install_brew_libs

trap - INT TERM EXIT